# Generated by Django 2.1.2 on 2018-10-10 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_locations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movies',
            new_name='Movie',
        ),
    ]
